name: thunderbird
version: 68.2.2
summary: Mozilla Thunderbird email application
description: Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
confinement: strict
grade: stable
base: core18


apps:
  thunderbird:
    command: thunderbird
    command-chain:
      - set-up-gnupg
    extensions: [gnome-3-28]
    environment:
      DISABLE_WAYLAND: 1
      HOME: "$SNAP_USER_COMMON"
    common-id: com.thunderbird
    slots:
      - dbus-daemon
    plugs:
      - avahi-observe
      - browser-support
      - cups-control
      - gsettings
      - gpg-keys
      - network
      - network-control
      - opengl
      - pulseaudio
      - removable-media
      - home

parts:
  gnupg:
    plugin: dump
    source: gnupg
    stage-packages: 
      - gpg
      - gpg-agent
      - gpgconf
      - pinentry-curses
      - pinentry-gnome3
      - rsync
      - gcr
      - libgcr-ui-3-1

  thunderbird:
    plugin: dump
    source: https://archive.mozilla.org/pub/thunderbird/releases/68.2.2/linux-x86_64/en-GB/thunderbird-68.2.2.tar.bz2
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      - libasound2
      - libpulse0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
      - libassuan0
      - libnpth0
      - libblkid1
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblzma5
      - libmount1
      - libpcre3
      - libselinux1
      - libsystemd0
      - libudev1
      - libuuid1
      - zlib1g
      - liblz4-1
      - libstdc++6
      - libtinfo5
      - libncursesw5
      - libgtk2.0-0
    organize:
      "snap/thunderbird/current/usr/*": usr/lib/thunderbird
      
  magic:
    after: [thunderbird]
    plugin: nil
    stage-packages:
      - shared-mime-info
    override-build: |
      snapcraftctl build
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/mime
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.thunderbird
      
layout:
  /etc/gnupg:
    bind: $SNAP/etc/gnupg
  /usr/bin/gpg:
    bind-file: $SNAP/gpg
  /usr/bin/gpg-agent:
    bind-file: $SNAP/usr/bin/gpg-agent
  /usr/bin/gpg-connect-agent:
    bind-file: $SNAP/usr/bin/gpg-connect-agent
  /usr/bin/gpgconf:
    bind-file: $SNAP/usr/bin/gpgconf
  /usr/lib/gnupg:
    bind: $SNAP/usr/lib/gnupg
  /usr/share/gnupg:
    bind: $SNAP/usr/share/gnupg
  /usr/bin/pinentry:
    bind-file: $SNAP/usr/bin/pinentry-gnome3
  /usr/lib/gcr:
    bind: $SNAP/usr/lib/gcr
